Apply tls to redis config
madfish-solutions/oko-wallet pull request #299
Opened 2023-02-23 13:37 UTC by LikoIlya

2023-02-23 13:48 UTC, lourenc requested changes

2023-02-23 13:48 UTC, lourenc commented on apps/backend/src/config/redis/guards.ts
> +    config.tls = Boolean(env.REDIS_TLS);
`Boolean("false") === true`

2023-02-23 14:06 UTC, LikoIlya commented on apps/backend/src/config/redis/guards.ts
> +    config.tls = Boolean(env.REDIS_TLS);
Fixed

2023-02-23 14:38 UTC, lourenc approved these changes

2023-02-24 08:59 UTC, unixvb approved these changes

2023-02-24 08:59 UTC, merged